# Generated by Django 5.2.11 on 2026-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_course_options_alter_instructor_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentsurvey",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_range_1_to_5",
            ),
        ),
    ]
